name: social_feed_api
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0
  dio: ^4.0.4
  retrofit: ^3.0.1+1
  package_info_plus: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  retrofit_generator: '>=4.0.0 <5.0.0'
flutter: